fix: run lighthouse on pr

diff --git a/.github/workflows/run-lighthouse-pr.yaml b/.github/workflows/run-lighthouse-pr.yaml
--- a/.github/workflows/run-lighthouse-pr.yaml
+++ b/.github/workflows/run-lighthouse-pr.yaml
@@ -1,25 +1,19 @@
-name: Page Speed Insights Check (PR CI)
+name: Run Lighthouse CI on PR
 on: [pull_request]
 jobs:
-  PSI:
+  lhci:
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Get branch name
-        id: branch-name
-        uses: tj-actions/branch-names@v6
-      - uses: cschleiden/replace-tokens@v1
+      - uses: actions/checkout@v1
+      - name: Use Node.js 18.12.0
+        uses: actions/setup-node@v1
         with:
-          files: '["./.github/lighthouse/lighthouserc.json"]'
-        env:
-          PSI_API_KEY: ${{ secrets.PSI_API_KEY }}
-      - name: Audit URLs using PSI
-        uses: treosh/lighthouse-ci-action@v9
-        with:
-          urls: |
-            https://${{ steps.branch-name.outputs.current_branch }}--helix-project-boilerplate--dylandepass.hlx.live/
-          runs: 10
-          configPath: ./.github/lighthouse/lighthouserc.json
-          uploadArtifacts: true # save results as an action artifacts
-          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL }}
-          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
+          node-version: 18.12.0
+      - name: npm install
+        run: |
+          npm install
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.11.x
+          lhci autorun || echo "LHCI failed!"
